FROM scratch

COPY target/armv7-unknown-linux-musleabihf/release/cdu \
    target/armv7-unknown-linux-musleabihf/release/hcc \
    target/armv7-unknown-linux-musleabihf/release/hcc-pushover \
    target/armv7-unknown-linux-musleabihf/release/hcc-server \
    target/armv7-unknown-linux-musleabihf/release/po \
    target/armv7-unknown-linux-musleabihf/release/pop \
    target/armv7-unknown-linux-musleabihf/release/wfs /

CMD ["/wfs"]
